import "@/app/globals.css";
import { PageWrapper } from "@/components";
import { i18n } from "@/i18n";
import { isLocales } from "@/lib/helpers/i18n-guards";
import { getComponentTranslation } from "@/lib/services";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Footer, Navbar } from "./_components";

export const metadata: Metadata = {
  title: "Teleferico Cerro Otto",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ locale }));
}

export default async function InstitutionalLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!isLocales(locale)) {
    notFound();
  }

  const { ok, data } = await getComponentTranslation(locale, "navbar");
  // TODO: Mejorar respuesta de interfaz en caso de que falle la llamada
  if (!ok) throw new Error("No se pudo recuperar el contenido del Navbar");

  return (
    <div className="leading-8">
      <Navbar items={data.data[0].jsonValue.items} />
      <main className="relative -top-[5rem] min-h-screen">
        <PageWrapper>{children}</PageWrapper>
      </main>
      <Footer locale={locale} />
    </div>
  );
}
