import { Providers } from "@/app/providers";
import { PageWrapper } from "@/components";
import { i18n } from "@/i18n";
import type { Locales } from "@/types";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { SWRConfig } from "swr";
import "../../globals.css";
import { Footer, Navbar } from "./_components";
import { getNavbarItems } from "@/lib/services";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ locale: locale }));
}

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function InstitutionalLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locales }>;
}>) {
  const { locale } = await params;
  const { ok, data } = await getNavbarItems(locale);
  // TODO: Mejorar respuesta de interfaz en caso de que falle la llamada
  if (!ok) throw new Error("No se pudo recuperar el contenido del Navbar");

  return (
    <html lang={locale}>
      <body className={`antialiased ${outfit.className}`}>
        <Providers>
          <SWRConfig
            value={{
              revalidateOnFocus: true,
              refreshWhenOffline: false,
              focusThrottleInterval: 6000,
            }}
          >
            <div className="leading-8">
              <Navbar items={data.data.components[0].items} />
              <main className="relative -top-[5rem] min-h-screen">
                <PageWrapper>{children}</PageWrapper>
              </main>
              <Footer locale={locale} />
            </div>
          </SWRConfig>
        </Providers>
      </body>
    </html>
  );
}
