import { Providers } from "@/app/providers";
import { PageWrapper } from "@/components";
import "@/app/globals.css";
import { i18n } from "@/i18n";
import { getComponentTranslation } from "@/lib/services";
import type { Locales } from "@/types";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { Footer, Navbar } from "./_components";

type Params = { params: Promise<{ locale: Locales }> };

export const dynamicParams = false;

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ locale }));
}

const SITE_ORIGIN = process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";

export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const { locale } = await params;
  const langs = Object.fromEntries(
    i18n.locales.map((l) => [l, `${SITE_ORIGIN}/${l}`]),
  );

  return {
    title: "Teleferico Cerro Otto",
    description: "Generated by create next app",
    alternates: {
      canonical: `${SITE_ORIGIN}/${locale}`,
      languages: langs,
    },
  };
}

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
});

export default async function InstitutionalLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locales }>;
}>) {
  const { locale } = await params;
  const { ok, data } = await getComponentTranslation(locale, "navbar");
  // TODO: Mejorar respuesta de interfaz en caso de que falle la llamada
  if (!ok) throw new Error("No se pudo recuperar el contenido del Navbar");

  return (
    <html lang={locale ?? i18n.defaultLocale}>
      <body className={`antialiased ${outfit.className}`}>
        <Providers>
          <div className="leading-8">
            <Navbar items={data.data[0].jsonValue.items} />
            <main className="relative -top-[5rem] min-h-screen">
              <PageWrapper>{children}</PageWrapper>
            </main>
            <Footer locale={locale} />
          </div>
        </Providers>
      </body>
    </html>
  );
}
