runtime: nodejs20
instance_class: %INSTANCE_CLASS%

env_variables:
  NODE_ENV: %NODE_ENV%
  HOST: %HOST%
  DATABASE_CLIENT: %DATABASE_CLIENT%
  DATABASE_NAME: %DATABASE_NAME%
  DATABASE_USERNAME: %DATABASE_USERNAME%
  DATABASE_PASSWORD: %DATABASE_PASSWORD%
  INSTANCE_CONNECTION_NAME: %INSTANCE_CONNECTION_NAME%
  GCS_BUCKET_NAME: %GCS_BUCKET_NAME%
  GCS_BASE_PATH: %GCS_BASE_PATH%
  APP_KEYS: %APP_KEYS%
  API_TOKEN_SALT: %API_TOKEN_SALT%
  ADMIN_JWT_SECRET: %ADMIN_JWT_SECRET%
  TRANSFER_TOKEN_SALT: %TRANSFER_TOKEN_SALT%
  JWT_SECRET: %JWT_SECRET%

build_env_variables:
  NODE_ENV: %NODE_ENV%

beta_settings:
  cloud_sql_instances: %INSTANCE_CONNECTION_NAME%
