export const CACHE_TAGS = {
  USERS: "users",
  SERVICE_STATE: "service-state",
  NAVITEMS: "navitems",
  ACTIVITIES_CONTENT: "content/activities",
  CONTACT_CONTENT: "content/contact",
  EXPLORE_CONTENT: "content/explore",
  FAQS_CONTENT: "content/faqs",
  FOUNDATION_CONTENT: "content/foundation",
  HOME_CONTENT: "content/",
  JOBS_CONTENT: "content/jobs",
  LOCATION_CONTENT: "content/location",
  POLICIES_CONTENT: "content/policies",
  PRICINGSCHEDULES_CONTENT: "content/pricing-schedules",
};
