export const CACHE_TAGS = {
  ACTIVITIES_CONTENT: "page-content/activities",
  CONTACT_CONTENT: "page-content/contact",
  EXPLORE_CONTENT: "page-content/explore",
  FAQS_CONTENT: "page-content/faqs",
  FOOTER: "footer",
  FORMS: "forms",
  FOUNDATION_CONTENT: "page-content/foundation",
  HOME_CONTENT: "page-content/",
  HOURS_OVERVIEW: "hours-overview",
  JOBS_CONTENT: "page-content/jobs",
  LOCATION_CONTENT: "page-content/location",
  NAVITEMS: "navitems",
  POLICIES_CONTENT: "page-content/policies",
  PRICINGSCHEDULES_CONTENT: "page-content/pricing-schedules",
  SCHEDULES: "schedules",
  SERVICE_BUTTON: "service-button",
  SERVICE_STATE: "service-state",
  USERS: "users",
} as const;
