import { ROUTES } from "./routes.const";

export const PAGE_TAG_PREFIX = "page-content";

const PAGE_CONTENT_CACHE_TAGS = {
  ACTIVITIES_CONTENT: `${PAGE_TAG_PREFIX}${ROUTES.ACTIVITIES}`,
  CONTACT_CONTENT: `${PAGE_TAG_PREFIX}${ROUTES.CONTACT}`,
  EXPLORE_CONTENT: `${PAGE_TAG_PREFIX}${ROUTES.EXPLORE}`,
  FAQS_CONTENT: `${PAGE_TAG_PREFIX}${ROUTES.FAQS}`,
  FOUNDATION_CONTENT: `${PAGE_TAG_PREFIX}${ROUTES.FOUNDATION}`,
  HOME_CONTENT: `${PAGE_TAG_PREFIX}${ROUTES.HOME}`,
  JOBS_CONTENT: `${PAGE_TAG_PREFIX}${ROUTES.JOBS}`,
  LOCATION_CONTENT: `${PAGE_TAG_PREFIX}${ROUTES.LOCATION}`,
  POLICIES_CONTENT: `${PAGE_TAG_PREFIX}${ROUTES.POLICIES}`,
  PRICINGSCHEDULES_CONTENT: `${PAGE_TAG_PREFIX}${ROUTES.PRICINGSCHEDULES}`,
} as const;

const COMPONENTS_CACHE_TAGS = {
  FOOTER: "footer",
  FORMS: "forms",
  HOURS_OVERVIEW: "hours-overview",
  NAVITEMS: "navitems",
  SCHEDULES: "schedules",
  SERVICE_BUTTON: "service-button",
  SERVICE_STATE: "service-state",
  USERS: "users",
} as const;

export const CACHE_TAGS = {
  ...PAGE_CONTENT_CACHE_TAGS,
  ...COMPONENTS_CACHE_TAGS,
} as const;
