import "@/app/globals.css";
import { Providers } from "@/app/providers";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Outfit } from "next/font/google";

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico?v=2",
    shortcut: "/favicon.ico?v=2",
    // Add apple-touch-icon once provided in /public
  },
};

export default function AdministrationLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es-AR">
      <body>
        <div className={`antialiased ${outfit.className}`}>
          <Providers>
            <SessionProvider>{children}</SessionProvider>
          </Providers>
        </div>
      </body>
    </html>
  );
}
