import { Providers } from "@/app/providers";
import type { Metadata } from "next";
import { Footer, Navbar } from "./_components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>
          <div className="">
            <Navbar />
            <main className="flex min-h-screen flex-col justify-between">
              {children}
            </main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
